// <auto-generated />
using System;
using G3Transportes.WebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace G3Transportes.WebApi.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20200402194243_20200402_1642")]
    partial class _20200402_1642
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("G3Transportes.WebApi.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Arquivo")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Anexo");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Caminhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Capacidade")
                        .HasColumnType("double");

                    b.Property<int?>("IdMotorista")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Placa")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("IdMotorista");

                    b.ToTable("Caminhao");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.CaminhaoAnexo", b =>
                {
                    b.Property<int>("IdCaminhao")
                        .HasColumnType("int");

                    b.Property<int>("IdAnexo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdCaminhao", "IdAnexo");

                    b.HasIndex("IdAnexo");

                    b.ToTable("CaminhaoAnexo");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contato")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Documento1")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Documento2")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndBairro")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndCep")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndCidade")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndComplemento")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndEstado")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndNumero")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndRua")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Telefone1")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Telefone2")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.ClienteAnexo", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdAnexo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdCliente", "IdAnexo");

                    b.HasIndex("IdAnexo");

                    b.ToTable("ClienteAnexo");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contato")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Documento1")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Documento2")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndBairro")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndCep")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndCidade")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndComplemento")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndEstado")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndNumero")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("EndRua")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Logomarca")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("SmtpHost")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<int>("SmtpPorta")
                        .HasColumnType("int");

                    b.Property<bool>("SmtpSSL")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SmtpSenha")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("SmtpUsuario")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Telefone1")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Telefone2")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Configuracao");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Baixado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataBaixa")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Favorecido")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<int?>("IdCaminhao")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPagamento")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.Property<double>("ValorAcrescimo")
                        .HasColumnType("double");

                    b.Property<double>("ValorBaixado")
                        .HasColumnType("double");

                    b.Property<double>("ValorBruto")
                        .HasColumnType("double");

                    b.Property<double>("ValorDesconto")
                        .HasColumnType("double");

                    b.Property<double>("ValorLiquido")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCaminhao");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdFormaPagamento");

                    b.HasIndex("IdPedido");

                    b.ToTable("Lancamento");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Documento1")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Documento2")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Documento3")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Telefone1")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Telefone2")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Telefone3")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Motorista");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.MotoristaAnexo", b =>
                {
                    b.Property<int>("IdMotorista")
                        .HasColumnType("int");

                    b.Property<int>("IdAnexo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdMotorista", "IdAnexo");

                    b.HasIndex("IdAnexo");

                    b.ToTable("MotoristaAnexo");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataColeta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFinalizado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destinatario")
                        .HasColumnType("text");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdCaminhao")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("LocalColeta")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("OrdemServico")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<double>("Quantidade")
                        .HasColumnType("double");

                    b.Property<double>("ValorBruto")
                        .HasColumnType("double");

                    b.Property<double>("ValorComissao")
                        .HasColumnType("double");

                    b.Property<double>("ValorFrete")
                        .HasColumnType("double");

                    b.Property<double>("ValorLiquido")
                        .HasColumnType("double");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCaminhao");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.PedidoAnexo", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdAnexo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdPedido", "IdAnexo");

                    b.HasIndex("IdAnexo");

                    b.ToTable("PedidoAnexo");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Senha")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Caminhao", b =>
                {
                    b.HasOne("G3Transportes.WebApi.Models.Motorista", "Motorista")
                        .WithMany("Caminhoes")
                        .HasForeignKey("IdMotorista")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.CaminhaoAnexo", b =>
                {
                    b.HasOne("G3Transportes.WebApi.Models.Anexo", "Anexo")
                        .WithMany("Caminhoes")
                        .HasForeignKey("IdAnexo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3Transportes.WebApi.Models.Caminhao", "Caminhao")
                        .WithMany("Anexos")
                        .HasForeignKey("IdCaminhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.ClienteAnexo", b =>
                {
                    b.HasOne("G3Transportes.WebApi.Models.Anexo", "Anexo")
                        .WithMany("Clientes")
                        .HasForeignKey("IdAnexo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3Transportes.WebApi.Models.Cliente", "Cliente")
                        .WithMany("Anexos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Lancamento", b =>
                {
                    b.HasOne("G3Transportes.WebApi.Models.Caminhao", "Caminhao")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdCaminhao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("G3Transportes.WebApi.Models.Cliente", "Cliente")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("G3Transportes.WebApi.Models.FormaPagamento", "FormaPagamento")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdFormaPagamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G3Transportes.WebApi.Models.Pedido", "Pedido")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.MotoristaAnexo", b =>
                {
                    b.HasOne("G3Transportes.WebApi.Models.Anexo", "Anexo")
                        .WithMany("Motoristas")
                        .HasForeignKey("IdAnexo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3Transportes.WebApi.Models.Motorista", "Motorista")
                        .WithMany("Anexos")
                        .HasForeignKey("IdMotorista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.Pedido", b =>
                {
                    b.HasOne("G3Transportes.WebApi.Models.Caminhao", "Caminhao")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCaminhao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G3Transportes.WebApi.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("G3Transportes.WebApi.Models.PedidoAnexo", b =>
                {
                    b.HasOne("G3Transportes.WebApi.Models.Anexo", "Anexo")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdAnexo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3Transportes.WebApi.Models.Pedido", "Pedido")
                        .WithMany("Anexos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
